# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a657f22c9d552b5fa8aae26b2a09bd90137590c88788a6825f305030fb055cfbff75aed161a3848d485116a5f2dd117ba61a93d80b089d9dcf7a5c48a8c833d0

test:
  secret_key_base: d8af691513ff911944a5712de987285ca78d7c9ed226414940fc22bd75f0d95888f3e017708c016dcfc4facacb55901d586b657708330095fc0c552d25044434

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
